database:
  host: 127.0.0.1
  port: 3306
  database: xzdp
  username: root
  password: root
  pool_max_conn: 100   #连接池 最大连接
  pool_max_idle: 10    #连接池 最大空闲等待
  pool_idle_time: 120  #空闲最大留存时间，从空闲开始，秒
  pool_life_time: 3600 #连接最大留存时间，从创建开始，秒
port: 8080